version: '3'

services:
  app:
    build: .
    # image: myapp:latest
    ports:
      - 5000:5000
    depends_on:
      - rabbitmq
    restart: on-failure
    environment:
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: 5000
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
  rabbitmq:
    image: rabbitmq:3-management
